# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
ZSH_THEME="awesomepanda"
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# Load aliases file.
. $HOME/.zsh/aliases.zsh

# Plugings
plugins=(git zsh-syntax-highlighting)

# Fuzzer
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/user/mambaforge/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/user/mambaforge/etc/profile.d/conda.sh" ]; then
        . "/home/user/mambaforge/etc/profile.d/conda.sh"
    else
        export PATH="/home/user/mambaforge/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

[[ -o interactive ]] && source $HOME/.expman/expman.zsh
